### ISSUE TITLE
allIds is redundant data

### ISSUE THREAD

**Issue by h3devin** [devinwl/redux-crud#1]
Remove the allIds reducer and write a selector that takes the byId reducer.

**Comment by wonderfulfrog** [comment]
Actually it's not necessarily redundant information.  The `allIds` array can be use to specify an order for the list of data - and using `Object.keys` from the `byId` object in the store should not be relied on for that.

https://stackoverflow.com/questions/42238802/redux-many-to-many-relationship/42257112?noredirect=1#comment71675068_42257112
